language: dart

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
  - $HOME/.pub-cache
  - $HOME/.dart_tool

jobs:
  include:
    - stage: Dart 2 stable
      dart: stable
      script:
        - dartanalyzer .
        - dartfmt --line-length=120 --dry-run --set-exit-if-changed .
        - pub run dependency_validator -i build_runner,build_test,build_web_compilers
        - pub run build_runner test --release -- -p chrome
        - pub run build_runner test -- -p chrome
    - stage: Dart 2 dev
      dart: dev
      script:
        - dartanalyzer .
        - pub run test -p chrome
        - pub run build_runner test -- -p chrome
