language: dart

dart:
  - stable
  - 1.24.3

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
  - $HOME/.pub-cache
  - $HOME/.dart_tool

script:
- dartanalyzer .
- pub run test -p chrome
