language: dart

dart:
  # We need 2.9.2 this to verify the Chrome MemoryInfo workaround: https://github.com/cleandart/react-dart/pull/280
  # TODO remove the workaround as well as this config once SDK lower bound is >=2.9.3
  - 2.9.2
  - stable
  - dev

# Re-use downloaded pub packages everywhere.
cache:
  directories:
  - $HOME/.pub-cache
  - $HOME/.dart_tool

before_script:
  - dartanalyzer .
  - |
    if [ "$TRAVIS_DART_VERSION" == "stable" ]; then
      dartfmt --line-length=120 --dry-run --set-exit-if-changed .
    fi
  - pub run dependency_validator -i build_runner,build_test,build_web_compilers

script:
  - pub run build_runner test --release -- --preset dart2js
  - pub run build_runner test -- --preset dartdevc
  - dart ./tool/run_consumer_tests.dart --orgName Workiva --repoName over_react --testCmd "pub run dart_dev test -P dartdevc"
