language: dart

dart:
  - '2.4.1'
  - stable
  - dev

# Re-use downloaded pub packages everywhere.
cache:
  directories:
  - $HOME/.pub-cache
  - $HOME/.dart_tool

before_script:
  - dartanalyzer .
  - dartfmt --line-length=120 --dry-run --set-exit-if-changed .
  - pub run dependency_validator -i build_runner,build_test,build_web_compilers

script:
  - pub run build_runner test --release -- -p chrome
  - pub run build_runner test -- -p chrome
