name: react
version: 5.0.0-dev.0
authors:
  - Samuel Hapák <samuel.hapak@gmail.com>
  - Greg Littlefield <greg.littlefield@workiva.com>
  - Claire Sarsam <claire.sarsam@workiva.com>
  - Aaron Lademann <aaron.lademann@workiva.com>
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: https://github.com/cleandart/react-dart
environment:
  sdk: '>=2.4.0 <3.0.0'
dependencies:
  js: ^0.6.1+1
  meta: ^1.1.6
dev_dependencies:
  build_runner: ^1.6.5
  build_test: ^0.10.8
  build_web_compilers: ^2.1.4
  dependency_validator: ^1.2.0
  test: ^1.6.5
