name: react
version: 4.7.0
authors:
  - Samuel Hapák <samuel.hapak@gmail.com>
  - Greg Littlefield <greg.littlefield@workiva.com>
  - Claire Sarsam <claire.sarsam@workiva.com>
  - Aaron Lademann <aaron.lademann@workiva.com>
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: https://github.com/cleandart/react-dart
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  js: ^0.6.0
  meta: ^1.1.6
dev_dependencies:
  build_runner: ">=0.6.0 <2.0.0"
  build_test: ">=0.9.0 <2.0.0"
  build_web_compilers: ">=0.2.0 <2.0.0"
  dart2_constant: ^1.0.0
  dependency_validator: ^1.2.0
  matcher: ^0.12.3+1
  test: ">=0.12.30 <2.0.0"
