name: react
author: Clean Team <clean@vacuumlabs.com>
version: 0.3.3
homepage: http://cleandart.github.io/react-dart/
description: Bindings of the ReactJS library for building interactive interfaces.
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: any
